=== Durss/mush-contagion/deploy/xml/userinfos.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema">
<!-- definition of simple type elements -->
	<xsd:element name="result" type="xsd:int" />
	<xsd:element name="pseudo" type="xsd:string" />
	<xsd:element name="avatar" type="xsd:string" />
	
<!-- definition of attributes -->
	<xsd:attribute name="uid" type="xsd:positiveInteger" />
	<xsd:attribute name="level" type="xsd:int" />
	<xsd:attribute name="ts" type="xsd:positiveInteger" />
	<xsd:attribute name="code" type="codeError" />

<!-- definition of complex type elements -->
	<xsd:element name="user">
		<xsd:complexType>
			<xsd:sequence>
				<xsd:element ref="pseudo" minOccurs="1" maxOccurs="1" />
				<xsd:element ref="avatar" minOccurs="0" maxOccurs="1" />
				<xsd:element ref="parent" minOccurs="0" maxOccurs="1" />
				<xsd:element ref="child" minOccurs="0" maxOccurs="1" />
			</xsd:sequence>
			<xsd:attribute ref="uid" use="required" />
			<xsd:attribute ref="level" use="required" />
		</xsd:complexType>
	</xsd:element>	
	
	<xsd:element name="child">
		<xsd:complexType>
			<xsd:sequence>
				<xsd:element ref="spore" minOccurs="0" maxOccurs="unbounded" />
			</xsd:sequence>
		</xsd:complexType>
	</xsd:element>
	<xsd:element name="parent">
		<xsd:complexType>
			<xsd:sequence>
				<xsd:element ref="spore" minOccurs="0" maxOccurs="unbounded" />
			</xsd:sequence>
		</xsd:complexType>
	</xsd:element>

	<xsd:element name="spore">
		<xsd:complexType>
			<xsd:attribute ref="uid" use="required" />
			<xsd:attribute ref="ts" use="required" />
		</xsd:complexType>
	</xsd:element>
	
	<xsd:element name="userinfos">
		<xsd:complexType>
			<xsd:sequence>
				<xsd:element ref="result" minOccurs="0" maxOccurs="1" />
				<xsd:element ref="user" minOccurs="0" maxOccurs="unbounded" />
				<xsd:element ref="error" minOccurs="0" maxOccurs="unbounded" />
			</xsd:sequence>
		</xsd:complexType>
	</xsd:element>
	
	<xsd:element name="error">
		<xsd:complexType mixed="true">
			<xsd:attribute ref="code" use="optional" />
		</xsd:complexType>
	</xsd:element>

<!-- definition of restricted type -->
	<xsd:simpleType name="codeError">
		<xsd:restriction base="xsd:string">
			<xsd:enumeration value="get" />
			<xsd:enumeration value="api" />
			<xsd:enumeration value="db" />
			<xsd:enumeration value="mush" />
		</xsd:restriction>
	</xsd:simpleType>

</xsd:schema>

=== Durss/mush-contagion/deploy/xml/userinfos.xml
<?xml version="1.0" encoding="UTF-8" standalone="yes" ?>
<userinfos	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
		xsi:noNamespaceSchemaLocation='http://localhost/mushcontagion/xml/userinfos.xsd'>
		<user uid="1" level="0">
			<pseudo>deepnight</pseudo>
			<avatar></avatar>
		</user>
		<user uid="2" level="1">
			<pseudo>bob</pseudo>
			<avatar></avatar>
			<parent>
				<spore uid="3" ts="1000000000"/>
			</parent>
		</user>
		<user uid="3" level="1">
			<pseudo>Franz</pseudo>
			<avatar>http://papayou.le.le/avatar.jpg</avatar>
			<parent>
				<spore uid="4" ts="999999999"/>
			</parent>
			<child>
				<spore uid="2" ts="1000000000"/>
			</child>
		</user>
		<user uid="4" level="0">
			<pseudo>dede</pseudo>
			<avatar>http://papayou.le.le/tronche.jpg</avatar>
			<child>
				<spore uid="3" ts="999999999"/>
				<spore uid="5" ts="999999999"/>
				<spore uid="6" ts="999999999"/>
			</child>
		</user>
		<user uid="5" level="1">
			<pseudo>peter</pseudo>
			<avatar></avatar>
			<parent>
				<spore uid="4" ts="999999999"/>
			</parent>
		</user>
		<user uid="6" level="1">
			<pseudo>pan</pseudo>
			<avatar></avatar>
			<parent>
				<spore uid="4" ts="999999999"/>
			</parent>
		</user>
</userinfos>
